### PR TITLE
feature/new-solid-annot: incoporated new solid metadata

### PR DESCRIPTION
**Pull request by scottkall**
Just let me know if you'd rather I work off of `develop` in the future instead of `master`

### CODE REVIEW

**Comment by sharlagelfand** [comment]
Let's just use master @scottkall -- it's a workflow I'm more comfortable with. Thanks!

**Review by sharlagelfand — APPROVED** [review]
@scottkall Can you help me understand the primary changes are here? I can see that `Patient Tumor Tissue` is now shown by default in the solid tumor database explorer instead of `Primary Site Subtype`, but is there a difference in the underlying data too? Just curious!

The code looks good to me though!

**Comment by sharlagelfand** [comment]
@scottkall wanted to follow up on this as i'm getting closer to finishing the next feature and it'd likely make sense to deploy it with this one. let me know if you'd like to merge this in yourself or like me to.

**Comment by scottkall** [comment]
@sharlagelfand honestly having trouble remembering the details at this point -- I just followed Mark's instruction as we were incorporating the expanded metadata newly given to us.

**Pull request merged**
